services:
  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
    command: ["node", "app.js"]

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:80"
